I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 278, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\BaiduNetdiskDownload\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "E:\BaiduNetdiskDownload\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "E:\BaiduNetdiskDownload\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "E:\BaiduNetdiskDownload\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "E:\BaiduNetdiskDownload\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
AI impact 1.0
Wed Dec  7 16:16:50 2022
